export const products = [
  // ─── GOLD SETS ────────────────────────────────────────────────────────────
  {
    id: "gs-1",
    slug: "classic-beauty-gold-set",
    name: "Classic Beauty Gold Set",
    sku: "GS-001",
    price: "Rs.840,000",
    priceNum: 840000,
    images: ["/gold-sets/Classic Beauty Gold Set.png"],
    category: "Gold Sets",
    isOnSale: false,
  },
  {
    id: "gs-2",
    slug: "crown-jewel-gold-set",
    name: "Crown Jewel Gold Set",
    sku: "GS-002",
    price: "Rs.960,000",
    priceNum: 960000,
    images: ["/gold-sets/Crown Jewel Gold Set.png"],
    category: "Gold Sets",
    isOnSale: true,
    originalPrice: "Rs.1,100,000",
  },
  {
    id: "gs-3",
    slug: "eternal-glow-gold-set",
    name: "Eternal Glow Gold Set",
    sku: "GS-003",
    price: "Rs.720,000",
    priceNum: 720000,
    images: ["/gold-sets/Eternal Glow Gold Set.png"],
    category: "Gold Sets",
    isOnSale: false,
  },
  {
    id: "gs-4",
    slug: "golden-blossom-set",
    name: "Golden Blossom Set",
    sku: "GS-004",
    price: "Rs.780,000",
    priceNum: 780000,
    images: ["/gold-sets/Golden Blossom Set.png"],
    category: "Gold Sets",
    isOnSale: false,
  },
  {
    id: "gs-5",
    slug: "golden-charm-set",
    name: "Golden Charm Set",
    sku: "GS-005",
    price: "Rs.850,000",
    priceNum: 850000,
    images: ["/gold-sets/Golden Charm Set.png"],
    category: "Gold Sets",
    isOnSale: true,
    originalPrice: "Rs.1,000,000",
  },
  {
    id: "gs-6",
    slug: "golden-era-set",
    name: "Golden Era Set",
    sku: "GS-006",
    price: "Rs.690,000",
    priceNum: 690000,
    images: ["/gold-sets/Golden Era Set.png"],
    category: "Gold Sets",
    isOnSale: false,
  },
  {
    id: "gs-7",
    slug: "golden-horizon-set",
    name: "Golden Horizon Set",
    sku: "GS-007",
    price: "Rs.710,000",
    priceNum: 710000,
    images: ["/gold-sets/Golden Horizon Set.png"],
    category: "Gold Sets",
    isOnSale: false,
  },
  {
    id: "gs-8",
    slug: "golden-radiance-set",
    name: "Golden Radiance Set",
    sku: "GS-008",
    price: "Rs.800,000",
    priceNum: 800000,
    images: ["/gold-sets/Golden Radiance Set.png"],
    category: "Gold Sets",
    isOnSale: false,
  },
  {
    id: "gs-9",
    slug: "golden-treasure-set",
    name: "Golden Treasure Set",
    sku: "GS-009",
    price: "Rs.760,000",
    priceNum: 760000,
    images: ["/gold-sets/Golden Treasure Set.png"],
    category: "Gold Sets",
    isOnSale: false,
  },
  {
    id: "gs-10",
    slug: "golden-whisper-set",
    name: "Golden Whisper Set",
    sku: "GS-010",
    price: "Rs.880,000",
    priceNum: 880000,
    images: ["/gold-sets/Golden Whisper Set.png"],
    category: "Gold Sets",
    isOnSale: true,
    originalPrice: "Rs.1,050,000",
  },
  {
    id: "gs-11",
    slug: "golden-symphony-set",
    name: "Golden Symphony Set",
    sku: "GS-011",
    price: "Rs.820,000",
    priceNum: 820000,
    images: ["/gold-sets/Golden symphony set.png"],
    category: "Gold Sets",
    isOnSale: false,
  },
  {
    id: "gs-12",
    slug: "graceful-shine-gold-set",
    name: "Graceful Shine Gold Set",
    sku: "GS-012",
    price: "Rs.870,000",
    priceNum: 870000,
    images: ["/gold-sets/Graceful Shine Gold Set.png"],
    category: "Gold Sets",
    isOnSale: false,
  },
  {
    id: "gs-13",
    slug: "heritage-charm-gold-set",
    name: "Heritage Charm Gold Set",
    sku: "GS-013",
    price: "Rs.790,000",
    priceNum: 790000,
    images: ["/gold-sets/Heritage Charm Gold Set.png"],
    category: "Gold Sets",
    isOnSale: false,
  },
  {
    id: "gs-14",
    slug: "majestic-aura-gold-set",
    name: "Majestic Aura Gold Set",
    sku: "GS-014",
    price: "Rs.930,000",
    priceNum: 930000,
    images: ["/gold-sets/Majestic Aura Gold Set.png"],
    category: "Gold Sets",
    isOnSale: true,
    originalPrice: "Rs.1,100,000",
  },
  {
    id: "gs-15",
    slug: "ornate-elegance-gold-set",
    name: "Ornate Elegance Gold Set",
    sku: "GS-015",
    price: "Rs.950,000",
    priceNum: 950000,
    images: ["/gold-sets/Ornate Elegance Gold Set.png"],
    category: "Gold Sets",
    isOnSale: false,
  },
  {
    id: "gs-16",
    slug: "pure-grace-gold-set",
    name: "Pure Grace Gold Set",
    sku: "GS-016",
    price: "Rs.860,000",
    priceNum: 860000,
    images: ["/gold-sets/Pure Grace Gold Set.png"],
    category: "Gold Sets",
    isOnSale: false,
  },
  {
    id: "gs-17",
    slug: "radiant-queen-gold-set",
    name: "Radiant Queen Gold Set",
    sku: "GS-017",
    price: "Rs.910,000",
    priceNum: 910000,
    images: ["/gold-sets/Radiant Queen Gold Set.png"],
    category: "Gold Sets",
    isOnSale: true,
    originalPrice: "Rs.1,080,000",
  },
  {
    id: "gs-18",
    slug: "regal-touch-gold-set",
    name: "Regal Touch Gold Set",
    sku: "GS-018",
    price: "Rs.830,000",
    priceNum: 830000,
    images: ["/gold-sets/Regal Touch Gold Set.png"],
    category: "Gold Sets",
    isOnSale: false,
  },
  {
    id: "gs-19",
    slug: "royal-heritage-gold-set",
    name: "Royal Heritage Gold Set",
    sku: "GS-019",
    price: "Rs.990,000",
    priceNum: 990000,
    images: ["/gold-sets/Royal Heritage Gold Set.png"],
    category: "Gold Sets",
    isOnSale: false,
  },
  {
    id: "gs-20",
    slug: "royal-charm-gold-set",
    name: "Royal Charm Gold Set",
    sku: "GS-020",
    price: "Rs.975,000",
    priceNum: 975000,
    images: ["/gold-sets/Royal charm gold set.png"],
    category: "Gold Sets",
    isOnSale: true,
    originalPrice: "Rs.1,150,000",
  },
  {
    id: "gs-21",
    slug: "starry-gold-set",
    name: "Starry Gold Set",
    sku: "GS-021",
    price: "Rs.680,000",
    priceNum: 680000,
    images: ["/gold-sets/Starry Gold Set.png"],
    category: "Gold Sets",
    isOnSale: false,
  },

  // ─── BRIDAL SETS ─────────────────────────────────────────────────────────
  {
    id: "bs-1",
    slug: "celestial-charm-bridal-set",
    name: "Celestial Charm Bridal Set",
    sku: "BS-001",
    price: "Rs.1,450,000",
    priceNum: 1450000,
    images: ["/bridal-sets/Celestial Charm Bridal Set.png"],
    category: "Bridal Sets",
    isOnSale: false,
  },
  {
    id: "bs-2",
    slug: "eternal-glow-bridal-set",
    name: "Eternal Glow Bridal Set",
    sku: "BS-002",
    price: "Rs.1,200,000",
    priceNum: 1200000,
    images: ["/bridal-sets/Eternal Glow Bridal Set.png"],
    category: "Bridal Sets",
    isOnSale: true,
    originalPrice: "Rs.1,450,000",
  },
  {
    id: "bs-3",
    slug: "golden-aura-bridal-set",
    name: "Golden Aura Bridal Set",
    sku: "BS-003",
    price: "Rs.1,350,000",
    priceNum: 1350000,
    images: ["/bridal-sets/Golden Aura Bridal Set.png"],
    category: "Bridal Sets",
    isOnSale: false,
  },
  {
    id: "bs-4",
    slug: "golden-blossom-bridal-set",
    name: "Golden Blossom Bridal Set",
    sku: "BS-004",
    price: "Rs.1,280,000",
    priceNum: 1280000,
    images: ["/bridal-sets/Golden Blossom Bridal Set.png"],
    category: "Bridal Sets",
    isOnSale: false,
  },
  {
    id: "bs-5",
    slug: "majestic-dream-bridal-set",
    name: "Majestic Dream Bridal Set",
    sku: "BS-005",
    price: "Rs.1,550,000",
    priceNum: 1550000,
    images: ["/bridal-sets/Majestic Dream Bridal Set.png"],
    category: "Bridal Sets",
    isOnSale: true,
    originalPrice: "Rs.1,800,000",
  },
  {
    id: "bs-6",
    slug: "queens-grace-bridal-set",
    name: "Queen's Grace Bridal Set",
    sku: "BS-006",
    price: "Rs.1,650,000",
    priceNum: 1650000,
    images: ["/bridal-sets/Queen's Grace Bridal Set.png"],
    category: "Bridal Sets",
    isOnSale: false,
  },
  {
    id: "bs-7",
    slug: "radiant-pearl-bridal-set",
    name: "Radiant Pearl Bridal Set",
    sku: "BS-007",
    price: "Rs.1,100,000",
    priceNum: 1100000,
    images: ["/bridal-sets/Radiant Pearl Bridal Set.png"],
    category: "Bridal Sets",
    isOnSale: false,
  },
  {
    id: "bs-8",
    slug: "royal-heritage-bridal-set",
    name: "Royal Heritage Bridal Set",
    sku: "BS-008",
    price: "Rs.1,750,000",
    priceNum: 1750000,
    images: ["/bridal-sets/Royal Heritage Bridal Set.png"],
    category: "Bridal Sets",
    isOnSale: false,
  },
  {
    id: "bs-9",
    slug: "timeless-elegance-bridal-set",
    name: "Timeless Elegance Bridal Set",
    sku: "BS-009",
    price: "Rs.1,380,000",
    priceNum: 1380000,
    images: ["/bridal-sets/Timeless Elegance Bridal Set.png"],
    category: "Bridal Sets",
    isOnSale: true,
    originalPrice: "Rs.1,600,000",
  },

  // ─── BANGLES & KARA ──────────────────────────────────────────────────────
  {
    id: "bk-1",
    slug: "golden-harmony-bangles",
    name: "Golden Harmony Bangles",
    sku: "BK-001",
    price: "Rs.320,000",
    priceNum: 320000,
    images: ["/bangles-kara/Golden-harmony-bangles.png"],
    category: "Bangles & Kara",
    isOnSale: false,
  },
  {
    id: "bk-2",
    slug: "classic-treasure-kara",
    name: "Classic Treasure Kara",
    sku: "BK-002",
    price: "Rs.280,000",
    priceNum: 280000,
    images: ["/bangles-kara/classic-treasure-kara.png"],
    category: "Bangles & Kara",
    isOnSale: false,
  },
  {
    id: "bk-3",
    slug: "floral-symphony-kara",
    name: "Floral Symphony Kara",
    sku: "BK-003",
    price: "Rs.295,000",
    priceNum: 295000,
    images: ["/bangles-kara/floral-symphony-kara.png"],
    category: "Bangles & Kara",
    isOnSale: true,
    originalPrice: "Rs.360,000",
  },
  {
    id: "bk-4",
    slug: "golden-crown-bangles",
    name: "Golden Crown Bangles",
    sku: "BK-004",
    price: "Rs.350,000",
    priceNum: 350000,
    images: ["/bangles-kara/golden-crown-bangles.png"],
    category: "Bangles & Kara",
    isOnSale: false,
  },
  {
    id: "bk-5",
    slug: "golden-flow-kara",
    name: "Golden Flow Kara",
    sku: "BK-005",
    price: "Rs.260,000",
    priceNum: 260000,
    images: ["/bangles-kara/golden-flow-kara.png"],
    category: "Bangles & Kara",
    isOnSale: false,
  },
  {
    id: "bk-6",
    slug: "golden-queen-bangles",
    name: "Golden Queen Bangles",
    sku: "BK-006",
    price: "Rs.380,000",
    priceNum: 380000,
    images: ["/bangles-kara/golden-queen-bangles.png"],
    category: "Bangles & Kara",
    isOnSale: true,
    originalPrice: "Rs.450,000",
  },
  {
    id: "bk-7",
    slug: "heritage-bride-bangles",
    name: "Heritage Bride Bangles",
    sku: "BK-007",
    price: "Rs.340,000",
    priceNum: 340000,
    images: ["/bangles-kara/heritage-bride-bangles.png"],
    category: "Bangles & Kara",
    isOnSale: false,
  },
  {
    id: "bk-8",
    slug: "moonlit-glow-kara",
    name: "Moonlit Glow Kara",
    sku: "BK-008",
    price: "Rs.275,000",
    priceNum: 275000,
    images: ["/bangles-kara/moonlit-glow-kara.png"],
    category: "Bangles & Kara",
    isOnSale: false,
  },
  {
    id: "bk-9",
    slug: "ornate-charm-bangles",
    name: "Ornate Charm Bangles",
    sku: "BK-009",
    price: "Rs.310,000",
    priceNum: 310000,
    images: ["/bangles-kara/ornate-charm-bangles.png"],
    category: "Bangles & Kara",
    isOnSale: false,
  },
  {
    id: "bk-10",
    slug: "radiant-bloom-kara",
    name: "Radiant Bloom Kara",
    sku: "BK-010",
    price: "Rs.290,000",
    priceNum: 290000,
    images: ["/bangles-kara/radiant-bloom-kara.png"],
    category: "Bangles & Kara",
    isOnSale: true,
    originalPrice: "Rs.350,000",
  },
  {
    id: "bk-11",
    slug: "regal-bride-bangles",
    name: "Regal Bride Bangles",
    sku: "BK-011",
    price: "Rs.360,000",
    priceNum: 360000,
    images: ["/bangles-kara/regal-bride-bangles.png"],
    category: "Bangles & Kara",
    isOnSale: false,
  },
  {
    id: "bk-12",
    slug: "royal-heritage-kara",
    name: "Royal Heritage Kara",
    sku: "BK-012",
    price: "Rs.300,000",
    priceNum: 300000,
    images: ["/bangles-kara/royal-heritage-kara.png"],
    category: "Bangles & Kara",
    isOnSale: false,
  },
  {
    id: "bk-13",
    slug: "timeless-grace-kara",
    name: "Timeless Grace Kara",
    sku: "BK-013",
    price: "Rs.285,000",
    priceNum: 285000,
    images: ["/bangles-kara/timeless-grace-kara.png"],
    category: "Bangles & Kara",
    isOnSale: false,
  },

  // ─── MALA SETS ────────────────────────────────────────────────────────────
  {
    id: "ms-1",
    slug: "blossom-shine-mala",
    name: "Blossom Shine Mala",
    sku: "MS-001",
    price: "Rs.420,000",
    priceNum: 420000,
    images: ["/mala-sets/Blossom Shine Mala.png"],
    category: "Mala Sets",
    isOnSale: false,
  },
  {
    id: "ms-2",
    slug: "celestial-bloom-mala",
    name: "Celestial Bloom Mala",
    sku: "MS-002",
    price: "Rs.480,000",
    priceNum: 480000,
    images: ["/mala-sets/Celestial Bloom Mala.png"],
    category: "Mala Sets",
    isOnSale: true,
    originalPrice: "Rs.570,000",
  },
  {
    id: "ms-3",
    slug: "celestial-charm-mala",
    name: "Celestial Charm Mala",
    sku: "MS-003",
    price: "Rs.460,000",
    priceNum: 460000,
    images: ["/mala-sets/Celestial Charm Mala.png"],
    category: "Mala Sets",
    isOnSale: false,
  },
  {
    id: "ms-4",
    slug: "celestial-elegance-mala",
    name: "Celestial Elegance Mala",
    sku: "MS-004",
    price: "Rs.490,000",
    priceNum: 490000,
    images: ["/mala-sets/Celestial Elegance Mala.png"],
    category: "Mala Sets",
    isOnSale: false,
  },
  {
    id: "ms-5",
    slug: "divine-heritage-mala",
    name: "Divine Heritage Mala",
    sku: "MS-005",
    price: "Rs.510,000",
    priceNum: 510000,
    images: ["/mala-sets/Divine Heritage Mala.png"],
    category: "Mala Sets",
    isOnSale: false,
  },
  {
    id: "ms-6",
    slug: "divine-spark-mala",
    name: "Divine Spark Mala",
    sku: "MS-006",
    price: "Rs.395,000",
    priceNum: 395000,
    images: ["/mala-sets/Divine Spark Mala.png"],
    category: "Mala Sets",
    isOnSale: true,
    originalPrice: "Rs.470,000",
  },
  {
    id: "ms-7",
    slug: "eternal-flow-mala",
    name: "Eternal Flow Mala",
    sku: "MS-007",
    price: "Rs.370,000",
    priceNum: 370000,
    images: ["/mala-sets/Eternal Flow Mala.png"],
    category: "Mala Sets",
    isOnSale: false,
  },
  {
    id: "ms-8",
    slug: "floral-shine-mala",
    name: "Floral Shine Mala",
    sku: "MS-008",
    price: "Rs.445,000",
    priceNum: 445000,
    images: ["/mala-sets/Floral Shine Mala.png"],
    category: "Mala Sets",
    isOnSale: false,
  },
  {
    id: "ms-9",
    slug: "golden-aura-mala",
    name: "Golden Aura Mala",
    sku: "MS-009",
    price: "Rs.410,000",
    priceNum: 410000,
    images: ["/mala-sets/Golden Aura Mala.png"],
    category: "Mala Sets",
    isOnSale: false,
  },
  {
    id: "ms-10",
    slug: "golden-bliss-mala",
    name: "Golden Bliss Mala",
    sku: "MS-010",
    price: "Rs.455,000",
    priceNum: 455000,
    images: ["/mala-sets/Golden Bliss Mala.png"],
    category: "Mala Sets",
    isOnSale: false,
  },
  {
    id: "ms-11",
    slug: "golden-cascade-mala",
    name: "Golden Cascade Mala",
    sku: "MS-011",
    price: "Rs.500,000",
    priceNum: 500000,
    images: ["/mala-sets/Golden Cascade Mala.png"],
    category: "Mala Sets",
    isOnSale: true,
    originalPrice: "Rs.590,000",
  },
  {
    id: "ms-12",
    slug: "golden-harmony-mala",
    name: "Golden Harmony Mala",
    sku: "MS-012",
    price: "Rs.430,000",
    priceNum: 430000,
    images: ["/mala-sets/Golden Harmony Mala.png"],
    category: "Mala Sets",
    isOnSale: false,
  },
  {
    id: "ms-13",
    slug: "golden-radiance-mala",
    name: "Golden Radiance Mala",
    sku: "MS-013",
    price: "Rs.465,000",
    priceNum: 465000,
    images: ["/mala-sets/Golden Radiance Mala.png"],
    category: "Mala Sets",
    isOnSale: false,
  },
  {
    id: "ms-14",
    slug: "golden-symphony-mala",
    name: "Golden Symphony Mala",
    sku: "MS-014",
    price: "Rs.475,000",
    priceNum: 475000,
    images: ["/mala-sets/Golden Symphony Mala.png"],
    category: "Mala Sets",
    isOnSale: false,
  },
  {
    id: "ms-15",
    slug: "golden-treasure-mala",
    name: "Golden Treasure Mala",
    sku: "MS-015",
    price: "Rs.490,000",
    priceNum: 490000,
    images: ["/mala-sets/Golden Treasure Mala.png"],
    category: "Mala Sets",
    isOnSale: true,
    originalPrice: "Rs.580,000",
  },
  {
    id: "ms-16",
    slug: "heavenly-aura-mala",
    name: "Heavenly Aura Mala",
    sku: "MS-016",
    price: "Rs.440,000",
    priceNum: 440000,
    images: ["/mala-sets/Heavenly Aura Mala.png"],
    category: "Mala Sets",
    isOnSale: false,
  },
  {
    id: "ms-17",
    slug: "heritage-bloom-mala",
    name: "Heritage Bloom Mala",
    sku: "MS-017",
    price: "Rs.420,000",
    priceNum: 420000,
    images: ["/mala-sets/Heritage Bloom Mala.png"],
    category: "Mala Sets",
    isOnSale: false,
  },
  {
    id: "ms-18",
    slug: "heritage-glow-mala",
    name: "Heritage Glow Mala",
    sku: "MS-018",
    price: "Rs.410,000",
    priceNum: 410000,
    images: ["/mala-sets/Heritage Glow Mala.png"],
    category: "Mala Sets",
    isOnSale: false,
  },
  {
    id: "ms-19",
    slug: "heritage-shine-mala",
    name: "Heritage Shine Mala",
    sku: "MS-019",
    price: "Rs.450,000",
    priceNum: 450000,
    images: ["/mala-sets/Heritage Shine Mala.png"],
    category: "Mala Sets",
    isOnSale: false,
  },
  {
    id: "ms-20",
    slug: "majestic-dream-mala",
    name: "Majestic Dream Mala",
    sku: "MS-020",
    price: "Rs.480,000",
    priceNum: 480000,
    images: ["/mala-sets/Majestic Dream Mala.png"],
    category: "Mala Sets",
    isOnSale: false,
  },
  {
    id: "ms-21",
    slug: "majestic-pearl-mala",
    name: "Majestic Pearl Mala",
    sku: "MS-021",
    price: "Rs.470,000",
    priceNum: 470000,
    images: ["/mala-sets/Majestic Pearl Mala.png"],
    category: "Mala Sets",
    isOnSale: true,
    originalPrice: "Rs.560,000",
  },
  {
    id: "ms-22",
    slug: "moonlight-glow-mala",
    name: "Moonlight Glow Mala",
    sku: "MS-022",
    price: "Rs.460,000",
    priceNum: 460000,
    images: ["/mala-sets/Moonlight Glow Mala.png"],
    category: "Mala Sets",
    isOnSale: false,
  },
  {
    id: "ms-23",
    slug: "moonlit-glow-mala",
    name: "Moonlit Glow Mala",
    sku: "MS-023",
    price: "Rs.455,000",
    priceNum: 455000,
    images: ["/mala-sets/Moonlit Glow Mala.png"],
    category: "Mala Sets",
    isOnSale: false,
  },
  {
    id: "ms-24",
    slug: "pearl-cascade-mala",
    name: "Pearl Cascade Mala",
    sku: "MS-024",
    price: "Rs.380,000",
    priceNum: 380000,
    images: ["/mala-sets/Pearl Cascade Mala.png"],
    category: "Mala Sets",
    isOnSale: false,
  },
  {
    id: "ms-25",
    slug: "queens-grace-mala",
    name: "Queen's Grace Mala",
    sku: "MS-025",
    price: "Rs.520,000",
    priceNum: 520000,
    images: ["/mala-sets/Queen's Grace Mala.png"],
    category: "Mala Sets",
    isOnSale: true,
    originalPrice: "Rs.620,000",
  },
  {
    id: "ms-26",
    slug: "queens-legacy-mala",
    name: "Queen's Legacy Mala",
    sku: "MS-026",
    price: "Rs.510,000",
    priceNum: 510000,
    images: ["/mala-sets/Queen's Legacy Mala.png"],
    category: "Mala Sets",
    isOnSale: false,
  },
  {
    id: "ms-27",
    slug: "radiant-glow-mala",
    name: "Radiant Glow Mala",
    sku: "MS-027",
    price: "Rs.430,000",
    priceNum: 430000,
    images: ["/mala-sets/Radiant Glow Mala.png"],
    category: "Mala Sets",
    isOnSale: false,
  },
  {
    id: "ms-28",
    slug: "radiant-pearl-mala",
    name: "Radiant Pearl Mala",
    sku: "MS-028",
    price: "Rs.465,000",
    priceNum: 465000,
    images: ["/mala-sets/Radiant Pearl Mala.png"],
    category: "Mala Sets",
    isOnSale: false,
  },
  {
    id: "ms-29",
    slug: "regal-heritage-mala",
    name: "Regal Heritage Mala",
    sku: "MS-029",
    price: "Rs.395,000",
    priceNum: 395000,
    images: ["/mala-sets/Regal Heritage Mala.png"],
    category: "Mala Sets",
    isOnSale: false,
  },
  {
    id: "ms-30",
    slug: "royal-bloom-mala",
    name: "Royal Bloom Mala",
    sku: "MS-030",
    price: "Rs.415,000",
    priceNum: 415000,
    images: ["/mala-sets/Royal Bloom Mala.png"],
    category: "Mala Sets",
    isOnSale: false,
  },
  {
    id: "ms-31",
    slug: "timeless-treasure-mala",
    name: "Timeless Treasure Mala",
    sku: "MS-031",
    price: "Rs.440,000",
    priceNum: 440000,
    images: ["/mala-sets/Timeless Treasure Mala.png"],
    category: "Mala Sets",
    isOnSale: true,
    originalPrice: "Rs.520,000",
  },

  // ─── CHAIN & LOCKET SETS ─────────────────────────────────────────────────
  {
    id: "cl-1",
    slug: "classic-locket-chain",
    name: "Classic Locket Chain",
    sku: "CL-001",
    price: "Rs.120,000",
    priceNum: 120000,
    images: ["/chain-locket-sets/Classic Locket Chain.png"],
    category: "Chain & Locket Sets",
    isOnSale: false,
  },
  {
    id: "cl-2",
    slug: "elegant-gold-chain-locket",
    name: "Elegant Gold Chain & Locket",
    sku: "CL-002",
    price: "Rs.145,000",
    priceNum: 145000,
    images: ["/chain-locket-sets/Elegant Gold Chain & Locket.png"],
    category: "Chain & Locket Sets",
    isOnSale: true,
    originalPrice: "Rs.175,000",
  },
  {
    id: "cl-3",
    slug: "floral-charm-chain",
    name: "Floral Charm Chain",
    sku: "CL-003",
    price: "Rs.130,000",
    priceNum: 130000,
    images: ["/chain-locket-sets/Floral Charm Chain.png"],
    category: "Chain & Locket Sets",
    isOnSale: false,
  },
  {
    id: "cl-4",
    slug: "royal-pendant-chain",
    name: "Royal Pendant Chain",
    sku: "CL-004",
    price: "Rs.160,000",
    priceNum: 160000,
    images: ["/chain-locket-sets/Royal Pendant Chain.png"],
    category: "Chain & Locket Sets",
    isOnSale: false,
  },
  {
    id: "cs-1",
    slug: "celestial-charm-choker",
    name: "Celestial Charm Choker",
    sku: "CS-001",
    price: "Rs.185,000",
    priceNum: 185000,
    images: ["/choker-sets/Celestial Charm Choker.png"],
    category: "Choker Sets",
    isOnSale: false,
  },
  {
    id: "cs-2",
    slug: "eternal-grace-choker",
    name: "Eternal Grace Choker",
    sku: "CS-002",
    price: "Rs.210,000",
    priceNum: 210000,
    images: ["/choker-sets/Eternal Grace Choker.png"],
    category: "Choker Sets",
    isOnSale: true,
    originalPrice: "Rs.240,000",
  },
  {
    id: "cs-3",
    slug: "golden-blossom-choker",
    name: "Golden Blossom Choker",
    sku: "CS-003",
    price: "Rs.195,000",
    priceNum: 195000,
    images: ["/choker-sets/Golden Blossom Choker.png"],
    category: "Choker Sets",
    isOnSale: false,
  },
  {
    id: "cs-4",
    slug: "moonlit-elegance-choker",
    name: "Moonlit Elegance Choker",
    sku: "CS-004",
    price: "Rs.225,000",
    priceNum: 225000,
    images: ["/choker-sets/Moonlit Elegance Choker.png"],
    category: "Choker Sets",
    isOnSale: false,
  },
  {
    id: "cs-5",
    slug: "radiant-glow-choker",
    name: "Radiant Glow Choker",
    sku: "CS-005",
    price: "Rs.205,000",
    priceNum: 205000,
    images: ["/choker-sets/Radiant Glow Choker.png"],
    category: "Choker Sets",
    isOnSale: false,
  },
  {
    id: "cs-6",
    slug: "royal-velvet-choker",
    name: "Royal Velvet Choker",
    sku: "CS-006",
    price: "Rs.235,000",
    priceNum: 235000,
    images: ["/c1.png"],
    category: "Choker Sets",
    isOnSale: false,
  },
  {
    id: "cs-7",
    slug: "antique-gold-choker",
    name: "Antique Gold Choker",
    sku: "CS-007",
    price: "Rs.190,000",
    priceNum: 190000,
    images: ["/c2.png"],
    category: "Choker Sets",
    isOnSale: false,
  },
  {
    id: "cs-8",
    slug: "diamond-accent-choker",
    name: "Diamond Accent Choker",
    sku: "CS-008",
    price: "Rs.275,000",
    priceNum: 275000,
    images: ["/c3.png"],
    category: "Choker Sets",
    isOnSale: true,
    originalPrice: "Rs.310,000",
  },
  {
    id: "cs-9",
    slug: "vintage-pearl-choker",
    name: "Vintage Pearl Choker",
    sku: "CS-009",
    price: "Rs.215,000",
    priceNum: 215000,
    images: ["/c4.png"],
    category: "Choker Sets",
    isOnSale: false,
  },
  {
    id: "cs-10",
    slug: "modern-geometric-choker",
    name: "Modern Geometric Choker",
    sku: "CS-010",
    price: "Rs.180,000",
    priceNum: 180000,
    images: ["/c5.png"],
    category: "Choker Sets",
    isOnSale: false,
  },
  {
    id: "cs-11",
    slug: "heritage-filigree-choker",
    name: "Heritage Filigree Choker",
    sku: "CS-011",
    price: "Rs.255,000",
    priceNum: 255000,
    images: ["/c6.png"],
    category: "Choker Sets",
    isOnSale: false,
  },
];

export const categories = [
  "Gold Sets",
  "Bridal Sets",
  "Bangles & Kara",
  "Mala Sets",
  "Choker Sets",
  "Chain & Locket Sets",
];

export const categoryMetadata: Record<
  string,
  { color: string; image?: string }
> = {
  "Gold Sets": {
    color: "#1a1a1a",
    image: "/gold-sets/Classic Beauty Gold Set.png",
  },
  "Bridal Sets": {
    color: "#2d0a0a",
    image: "/bridal-sets/Timeless Elegance Bridal Set.png",
  },
  "Bangles & Kara": {
    color: "#0f172a",
    image: "/bangles-kara/golden-crown-bangles.png",
  },
  "Mala Sets": {
    color: "#1e293b",
    image: "/mala-sets/Celestial Bloom Mala.png",
  },
  "Choker Sets": {
    color: "#000000",
    image: "/choker-sets/Radiant Glow Choker.png",
  },
  "Chain & Locket Sets": {
    color: "#171717",
    image: "/chain-locket-sets/Royal Pendant Chain.png",
  },
  default: { color: "#111827", image: "/choker-sets/Celestial Charm Choker.png" },
};
