export const products = [
  {
    id: "1",
    slug: "gold-sets-1",
    name: "Exquisite Gold Set - G246",
    sku: "G246",
    price: "Rs.840,000",
    priceNum: 840000,
    images: ["/Gold-bracelet.jpg"],
    category: "Gold Sets",
    bullets: [
      "24K Gold Plated",
      "Intricate Design",
      "925 Sterling Silver base",
    ],
    isOnSale: false,
  },
  {
    id: "2",
    slug: "bridal-sets-1",
    name: "Imperial Bridal Set - B882",
    sku: "B882",
    price: "Rs.1,250,000",
    priceNum: 1250000,
    images: ["/Gold-bracelet.jpg"],
    category: "Bridal Sets",
    bullets: ["Full Wedding Collection", "Kundan Work", "Gold Electroplated"],
    isOnSale: true,
    originalPrice: "Rs.1,500,000",
  },
  {
    id: "3",
    slug: "bangles-kara-1",
    name: "Traditional Kara Pair - K992",
    sku: "K992",
    price: "Rs.320,000",
    priceNum: 320000,
    images: ["/Gold-bracelet.jpg"],
    category: "Bangles & Kara",
    bullets: ["Screw Opening", "Hand Carved", "925 Silver"],
    isOnSale: false,
  },
  {
    id: "4",
    slug: "mala-sets-1",
    name: "Royal Mala Set - M112",
    sku: "M112",
    price: "Rs.450,000",
    priceNum: 450000,
    images: ["/Gold-bracelet.jpg"],
    category: "Mala Sets",
    bullets: ["Multi-layer Beads", "Gold Accents", "Antique Finish"],
    isOnSale: true,
    originalPrice: "Rs.550,000",
  },
  {
    id: "5",
    slug: "choker-sets-1",
    name: "Modern Choker Set - C442",
    sku: "C442",
    price: "Rs.280,000",
    priceNum: 280000,
    images: ["/Gold-bracelet.jpg"],
    category: "Choker Sets",
    bullets: ["Adjustable Fit", "Contemporary Design", "Gold Plated"],
    isOnSale: false,
  },
  {
    id: "6",
    slug: "chain-locket-sets-1",
    name: "Elegant Chain & Locket - L552",
    sku: "L552",
    price: "Rs.120,000",
    priceNum: 120000,
    images: ["/Gold-bracelet.jpg"],
    category: "Chain & Locket Sets",
    bullets: ["Delicate Chain", "Heart Locket", "Everyday Wear"],
    isOnSale: true,
    originalPrice: "Rs.150,000",
  },
  {
    id: "7",
    slug: "gold-sets-2",
    name: "Heritage Gold Set - G248",
    sku: "G248",
    price: "Rs.760,000",
    priceNum: 760000,
    images: ["/Gold-bracelet.jpg"],
    category: "Gold Sets",
    bullets: ["Antique Gold Finish", "Lightweight base"],
    isOnSale: false,
  },
];

export const categories = [
  "Gold Sets",
  "Bridal Sets",
  "Bangles & Kara",
  "Mala Sets",
  "Choker Sets",
  "Chain & Locket Sets",
];
